ENABLE_TEMPLATE_PROCESSING=True
SUPERSET_FEATURE_EMBEDDED_SUPERSET=True
BABEL_DEFAULT_LOCALE = "zh"

# 10 year
WTF_CSRF_TIME_LIMIT=60 * 60 * 24 * 365 *10
WTF_CSRF_ENABLED = False
WTF_CSRF_TIME_LIMIT=None
SESSION_COOKIE_SAMESITE = 'Lax'
PUBLIC_ROLE_LIKE_GAMMA = True
SESSION_COOKIE_SECURE = False